include makefile.vars

LIBDFT_SRC			= libdft/src
#LIBDFT_TAG_FLAGS	?= -DCUSTOM_TAGS_FDOFFSET	# fdset offset tags
LIBDFT_TAG_FLAGS	?= -DCUSTOM_TAGS_BITSET=32	# bitset tags
CPPFLAGS			+= $(LIBDFT_TAG_FLAGS)

.PHONY: all
all: libdft

.PHONY: libdft
libdft: $(LIBDFT_SRC)
	cd $< && CPPFLAGS=$(CPPFLAGS) make

.PHONY: clean
clean: $(LIBDFT_SRC)
	cd $< && make clean

# vim: ai:ts=4:sw=4:et!:ft=make
