CC=clang
CXX=clang++
INSTALL=install
PYTHON=python
RM=rm
SED=sed
SVN=svn
TAR=tar
UNZIP=unzip
WGET=wget

BUILD_DIR=build

CONFIG_FLAGS_COMMON = --prefix=$(realpath $(BUILD_DIR)/..) CPPFLAGS=-I$(realpath $(BUILD_DIR)/../include) LDFLAGS=-L$(realpath $(BUILD_DIR)/../lib) PKG_CONFIG_PATH=$(realpath $(BUILD_DIR)/../lib/pkgconfig) PATH=$(realpath $(BUILD_DIR)/../bin):$(PATH) 

