##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################
ifdef PIN_ROOT
  CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
  PIN_ROOT := ./pin
  CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
endif
PIN_VERSION := $(shell head -1 $(PIN_ROOT)/README | tr -dc 0-9 | awk '{if ($$0 < 100) { print 10*$$0 } else { print $$0 }}')
ifeq ($(PIN_VERSION),)
  $(error Cannot determine Pin version.)
else
  $(info ## Using Pin v$(PIN_VERSION) from $(PIN_ROOT).)
  $(info ## Loading defaults from $(CONFIG_ROOT)/makefile.config.)
  include $(CONFIG_ROOT)/makefile.config
endif

ifneq ($(HOST_ARCH),ia32)
  $(info ## Running on $(HOST_ARCH) host. Targetting to ia32.)
  TARGET := ia32
  $(info ## Reloading defaults from $(CONFIG_ROOT)/makefile.config.)
  include $(CONFIG_ROOT)/makefile.config
endif

include Makefile.rules

ifeq ($(wildcard $(TOOLS_ROOT)/Config/makefile.default.rules),)
  $(warning Cannot include makefile.default.rules. This is caused because Pin assumes our code is located under PIN_ROOT. Fix this by running:)
  $(warning sed -i.bak 's/PIN_ROOT :=/PIN_ROOT ?=/' "$(CONFIG_ROOT)/makefile.unix.config")
  $(error Aborting)
else
  $(info ## Loading default rules for $(TOOLS_ROOT)/Config/makefile.default.rules.)
  include $(TOOLS_ROOT)/Config/makefile.default.rules
endif

##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################
